# Generated by Django 5.2.8 on 2025-11-25 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('land_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural'), ('mixed_use', 'Mixed Use')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available for Sale'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('size_square_meters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size_acres', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('land_use_purpose', models.CharField(blank=True, max_length=100)),
                ('topographical_features', models.JSONField(default=list)),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('has_installment_plan', models.BooleanField(default=False)),
                ('installment_months', models.IntegerField(default=0)),
                ('c_of_o_available', models.BooleanField(default=False)),
                ('survey_plan_available', models.BooleanField(default=False)),
                ('government_approval', models.BooleanField(default=False)),
                ('images', models.JSONField(default=list)),
                ('survey_plan_image', models.FileField(blank=True, null=True, upload_to='survey_plans/')),
                ('video_tour_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandInstallmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('total_months', models.IntegerField()),
                ('down_payment_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('monthly_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='properties_app.land')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reservation_duration_days', models.IntegerField(default=30)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('converted', 'Converted to Sale'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_reservations', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties_app.land')),
            ],
            options={
                'unique_together': {('land', 'customer')},
            },
        ),
    ]
