# Generated by Django 5.2.8 on 2025-11-25 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_reference', models.CharField(max_length=100, unique=True)),
                ('total_land_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('down_payment', 'Down Payment'), ('installment', 'Installment Payment'), ('reservation_fee', 'Reservation Fee'), ('legal_fee', 'Legal Fee'), ('documentation_fee', 'Documentation Fee')], default='full_payment', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('down_payment_paid', 'Down Payment Paid'), ('in_progress', 'Payment in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='draft', max_length=20)),
                ('down_payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('down_payment_paid', models.BooleanField(default=False)),
                ('total_installments', models.IntegerField(default=0)),
                ('completed_installments', models.IntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='purchase_agreements/')),
                ('legal_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('documentation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_purchases', to=settings.AUTH_USER_MODEL)),
                ('installment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties_app.landinstallmentplan')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='properties_app.land')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('down_payment', 'Down Payment'), ('installment', 'Installment Payment'), ('reservation_fee', 'Reservation Fee'), ('legal_fee', 'Legal Fee'), ('documentation_fee', 'Documentation Fee')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('ussd', 'USSD'), ('account', 'Bank Account')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_installment', models.BooleanField(default=False)),
                ('installment_number', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('flutterwave_tx_ref', models.CharField(blank=True, max_length=100, unique=True)),
                ('flutterwave_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('flutterwave_response', models.JSONField(blank=True, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments_app.landpurchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('flutterwave_tx_ref', models.CharField(max_length=100, unique=True)),
                ('flutterwave_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('is_failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments_app.landpayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('payment', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='payments_app.landpurchase')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('purchase', 'installment_number')},
            },
        ),
    ]
